replicaCount: 1

image:
  repository: jenkins/jenkins
  pullPolicy: IfNotPresent
  tag: "lts-jdk11"

nameOverride: "jenkins"
fullnameOverride: "jenkins"

service:
  type: ClusterIP
  port: 8080

ingress:
  enabled: true
  className: "nginx"
  hosts:
    - host: jenkins.localdev.me
      paths:
        - path: /
          pathType: ImplementationSpecific
resources: 
  limits:
    cpu: 1000m
    memory: 2Gi
  requests:
    cpu: 100m
    memory: 512Mi

livenessProbe:
  httpGet:
    path: /
    port: http
  initialDelaySeconds: 30
  periodSeconds: 10
readinessProbe:
  httpGet:
    path: /
    port: http
  initialDelaySeconds: 30
  periodSeconds: 10