replicaCount: 1

image:
  repository: sonatype/nexus3
  pullPolicy: IfNotPresent
  tag: "latest"

nameOverride: "nexus3"
fullnameOverride: "nexus3"

service:
  type: ClusterIP
  port: 8081

ingress:
  enabled: true
  className: "nginx"
  hosts:
    - host: nexus3.localdev.me
      paths:
        - path: /
          pathType: ImplementationSpecific
resources: 
  limits:
    cpu: 1000m
    memory: 2Gi
  requests:
    cpu: 100m
    memory: 512Mi

livenessProbe:
  httpGet:
    path: /
    port: http
  initialDelaySeconds: 30
  periodSeconds: 10
readinessProbe:
  httpGet:
    path: /
    port: http
  initialDelaySeconds: 30
  periodSeconds: 10